services:
  rocky10build:
    volumes:
      - rpm10rocky:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        os: $RL10
  rocky10buildreloc:
    command: ["-ba", "--with", "relocation"]
    volumes:
      - rpm10rocky:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        os: $RL10

volumes:
  rpm10rocky:
    name: rpm10rocky
