services:
  rocky10base:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        os: $RL10
    image: "aursu/php83build:${RL8TAG}-base"
  rocky9base:
    build:
      context: .
      dockerfile: Dockerfile.RL9.base
      args:
        os: $RL9
    image: "aursu/php83build:${RL9TAG}-base"
