services:
  rocky10dev:
    build:
      context: dev
      args:
        os: $RL10
    image: "ghcr.io/rpmbsys/php83build:${RL10TAG}-${DEVTAG}"
  rocky9dev:
    build:
      context: dev
      args:
        os: $RL9
    image: "ghcr.io/rpmbsys/php83build:${RL9TAG}-${DEVTAG}"
  rocky9dev2:
    build:
      context: dev
      args:
        os: $RL9
        image: dev2base
    image: "ghcr.io/rpmbsys/php83build:${RL9TAG}-dev2"
