services:
  rocky10dev:
    build:
      context: dev
      args:
        os: $RL10
    image: "aursu/php83build:${RL10TAG}-dev"
  rocky9dev:
    build:
      context: dev
      args:
        os: $RL9
    image: "aursu/php83build:${RL9TAG}-dev"
  rocky9dev2:
    build:
      context: dev
      args:
        os: $RL9
        image: dev2base
    image: "aursu/php83build:${RL9TAG}-dev2"
