version: "3"
services:
  centos7run:
    build:
      context: .
      args:
        centos: $OS7
    image: aursu/php83build:${OS7TAG}-runtime
  centos7devbase:
    build:
      context: .
      args:
        centos: $OS7
        image: node14dev
    image: aursu/php83build:${OS7TAG}-devbase
  centos7dev2base:
    build:
      context: .
      args:
        centos: $OS7
        image: node16dev
    image: aursu/php83build:${OS7TAG}-dev2base